### ISSUE TITLE
if the wifi ssid has configed before,can I use the method 

### ISSUE THREAD

**Issue by libinll** [ThanosFisherman/WifiUtils#2]
if the wifi ssid has configed before,can I use the method  " connectWith(SSID, "") " without password?
Must I use method  connectWith(SSID, "password") ?

**Comment by ThanosFisherman** [comment]
No you must always use the correct WiFi password string even if there's an already configured network because this library will clear the previous configuration on Androids < 6.0 and create a new one from scratch where possible. See [this](https://github.com/ThanosFisherman/WifiUtils/blob/067f570086d783905563154518d930cbf220bfc7/wifiutils/src/main/java/com/thanosfisherman/wifiutils/ConnectorUtils.java#L193)

**Comment by libinll** [comment]
You first clean the previous configuration before use the method 'connectToconfiguredNetWork'.Whatever  Androids < 6.0,it will clean the previous configuration.
Maybe we can clean the previous configuration after the network connect failed.
We do not need user to input password  when the network has configed.

**Comment by ThanosFisherman** [comment]
Is there any particular reason why you'd want to use an empty password String? Is it because you don't know the password in the first place but want to force WiFi to connect to that specific configured network?

Anyhow I will look into it when I find some time. Maybe there's indeed no need to clear the previous configuration and make a new one every time. In the meantime feel free to make a pull request with your suggested implementation but I will definitely take a look at it myself too.

**Comment by ThanosFisherman** [comment]
As of release 1.3.4 you can now enter an empty password string `""` This will make the lib look for an existing network configuration to connect to. If there is none, it will proceed as normal but probably fail unless the hotspot doesn't require authentication.
